const dotenv = require('dotenv');

dotenv.config();

module.exports = [
  process.env.IMAGE_0,
  process.env.IMAGE_1,
  process.env.IMAGE_2,
  process.env.IMAGE_3,
  process.env.IMAGE_4,
  process.env.IMAGE_5,
  process.env.IMAGE_6,
  process.env.IMAGE_7,
  process.env.IMAGE_8,
  process.env.IMAGE_9,
  process.env.IMAGE_10,
  process.env.IMAGE_11,
  process.env.IMAGE_12,
  process.env.IMAGE_13,
  process.env.IMAGE_14,
  process.env.IMAGE_15,
  process.env.IMAGE_16,
  process.env.IMAGE_17,
  process.env.IMAGE_18,
  process.env.IMAGE_19,
  process.env.IMAGE_20,
  process.env.IMAGE_21,
  process.env.IMAGE_22,
  process.env.IMAGE_23,
  process.env.IMAGE_24,
  process.env.IMAGE_25,
  process.env.IMAGE_26,
  process.env.IMAGE_27,
  process.env.IMAGE_28,
  process.env.IMAGE_29,
  process.env.IMAGE_30,
  process.env.IMAGE_31,
  process.env.IMAGE_32,
  process.env.IMAGE_33,
  process.env.IMAGE_34,
  process.env.IMAGE_35,
];
